LinearAlgebra.class NetTest.class NetMain.class: NetMain.java LinearAlgebraTest.java NetTest.java Matrix.java Net.java
	clear
	javac LinearAlgebraTest.java
	javac NetTest.java
	javac NetMain.java
	javac MetaNet.java
clean: 
	rm *.class
testLA: 
	clear
	java LinearAlgebraTest
testNet: 
	clear
	java NetTest
run:
	clear
	java NetMain

